### ISSUE TITLE
favicon mutable error

### ISSUE THREAD

**Issue by jahanvir** [fastn-stack/fastn-template#11]
fastn-Error: path: /, PackageError { message: "failed to parse ParseError { message: \"Header type `favicon` mutable: `false` argument not found for component `ftd.document`\", doc_id: \"fastn-community.github.io/doc-site\", line_number: 119 }" }

After cloning the template and serving it without any changes throwing this error.

**Comment by jahanvir** [comment]
This error was not happening earlier.

**Comment by amitu** [comment]
@jahanvir thanks for reporting this. We will look at it soon.

**Comment by gsalunke** [comment]
> @jahanvir thanks for reporting this. We will look at it soon.

Hey @jahanvir,

This issue can be fixed using below steps:
1. Edit `FASTN/ds.ftd` and add `favicon` property in page component like this - [Ref Code](https://github.com/fastn-stack/fastn-template/blob/8ec71b59135821ad88776c36a8180d487cac9fc5/FASTN/ds.ftd#L34)
2. Add `favicon` property and it's value to `doc-site.page` component of `FASTN/ds.ftd` - [Ref Code](https://github.com/fastn-stack/fastn-template/blob/8ec71b59135821ad88776c36a8180d487cac9fc5/FASTN/ds.ftd#L69) 
3. Update your `fastn` version with latest release [fastn Releases](https://github.com/fastn-stack/fastn/releases)

@amitu 
We have resolved this issue into [fastn-template](https://github.com/fastn-stack/fastn-template), so in future if anyone uses `fastn-template` they wont face it.

**Comment by amitu** [comment]
@jahanvir please re-open this issue if it does not work for you.

**Comment by jahanvir** [comment]
@amitu @gsalunke 

Issue is resolved, updating the fastn does the trick.
